package org.ual.hmis.equipo7;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ModificacionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private int browser = 0;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
	System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
	ChromeOptions chromeOptions = new ChromeOptions(); 
    chromeOptions.setHeadless(true);
    FirefoxOptions firefoxOptions = new FirefoxOptions(); 
    firefoxOptions.setHeadless(true); 
    
	browser = 1; //Chrome: 0 | Firefox: 1		
	driver = browser == 0 ? new ChromeDriver(chromeOptions) : new FirefoxDriver(firefoxOptions);
	
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificarCambioDescripcion() {
    driver.get("http://coresqlmgg.azurewebsites.net/");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.linkText("Create New")).click();
    vars.put("descripcionRandom", js.executeScript("return \"hmis-\" + Math.floor(Math.random()*1500000)"));
    driver.findElement(By.id("Description")).click();
    driver.findElement(By.id("Description")).sendKeys(vars.get("descripcionRandom").toString());
    String fecha = browser == 0 ? "04-04-2022" : "2022-04-04";
    driver.findElement(By.id("CreatedDate")).sendKeys(fecha);
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("descripcionRandom", js.executeScript("return \"hmis-\" + Math.floor(Math.random()*1500000)"));
    vars.put("nRows", driver.findElements(By.xpath("//tbody/tr")).size());
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(1)")).click();
    driver.findElement(By.id("Description")).click();
    driver.findElement(By.id("Description")).clear();
    driver.findElement(By.id("Description")).sendKeys(vars.get("descripcionRandom").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(1)")).getText(), is(vars.get("descripcionRandom").toString()));
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void modificarCambioFecha() {
    driver.get("http://coresqlmgg.azurewebsites.net/");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.linkText("Create New")).click();
    vars.put("descripcionRandom", js.executeScript("return \"hmis-\" + Math.floor(Math.random()*1500000)"));
    driver.findElement(By.id("Description")).click();
    driver.findElement(By.id("Description")).sendKeys(vars.get("descripcionRandom").toString());
    String fecha = browser == 0 ? "04-04-2022" : "2022-04-04";
    driver.findElement(By.id("CreatedDate")).sendKeys(fecha);
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("nRows", driver.findElements(By.xpath("//tbody/tr")).size());
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(1)")).click();
    driver.findElement(By.id("CreatedDate")).click();
    driver.findElement(By.id("CreatedDate")).clear();
    fecha = browser == 0 ? "01-01-2022" : "2022-01-01";
    driver.findElement(By.id("CreatedDate")).sendKeys(fecha);
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(2)")).getText(), is("2022-01-01"));
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void modificarErrorFecha() {
    driver.get("http://coresqlmgg.azurewebsites.net/");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.linkText("Create New")).click();
    vars.put("descripcionRandom", js.executeScript("return \"hmis-\" + Math.floor(Math.random()*1500000)"));
    driver.findElement(By.id("Description")).click();
    driver.findElement(By.id("Description")).sendKeys(vars.get("descripcionRandom").toString());
    String fecha = browser == 0 ? "04-04-2022" : "2022-04-04";
    driver.findElement(By.id("CreatedDate")).sendKeys(fecha);
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("nRows", driver.findElements(By.xpath("//tbody/tr")).size());
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(1)")).click();
    driver.findElement(By.id("CreatedDate")).click();
    driver.findElement(By.id("CreatedDate")).clear();
    driver.findElement(By.id("CreatedDate")).sendKeys("error");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("CreatedDate-error"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Back to List")).click();
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void modificarSinCambios() {
    driver.get("http://coresqlmgg.azurewebsites.net/");
    driver.manage().window().setSize(new Dimension(968, 1039));
    driver.findElement(By.linkText("Create New")).click();
    vars.put("descripcionRandom", js.executeScript("return \"hmis-\" + Math.floor(Math.random()*1500000)"));
    driver.findElement(By.id("Description")).click();
    driver.findElement(By.id("Description")).sendKeys(vars.get("descripcionRandom").toString());
    String fecha = browser == 0 ? "04-04-2022" : "2022-04-04";
    driver.findElement(By.id("CreatedDate")).sendKeys(fecha);
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("nRows", driver.findElements(By.xpath("//tbody/tr")).size());
    vars.put("descripcion", driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(1)")).getText());
    vars.put("fecha", driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(2)")).getText());
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(1)")).click();
    driver.findElement(By.linkText("Back to List")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(1)")).getText(), is(vars.get("descripcion").toString()));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") > td:nth-child(2)")).getText(), is(vars.get("fecha").toString()));
    driver.findElement(By.cssSelector("tr:nth-child(" + vars.get("nRows").toString() + ") a:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
